import { NgModule } from '@angular/core';
// import { CommonModule } from '@angular/common';
import { ProductListComponent } from './product-list.component';
import { ProductDetailComponent } from './product-detail.component';
import { ConvertToSpacesPipe } from '../shared/convert-to-spaces.pipe';
// import { StarComponent } from '../shared/star.component';
import { SharedModule } from '../shared/shared.module'
// import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ProductDetailGuard } from './product-detail.guard';

// Generated by CLI, then modified
  // ng g m products/product --flat -m app
    // -m app imports into app module

@NgModule({
  declarations: [
    // Moved here
    ProductListComponent,
    ProductDetailComponent,
    ConvertToSpacesPipe,
    // Moved to Shared
    // StarComponent,
  ],
  imports: [
    // Moved to Shared
    // CommonModule,
    // FormsModule,
    RouterModule,

    // Child Module Routing:
    RouterModule.forChild([
      { path: 'products', component: ProductListComponent},
      { path: 'products/:id', 
        canActivate: [ProductDetailGuard],
        component: ProductDetailComponent},
    ]),
    SharedModule,
  ]
})
export class ProductModule { }
