import { NgModule } from '@angular/core';
// import { CommonModule } from '@angular/common';
import { ProductListComponent } from './product-list.component';
import { ProductDetailComponent } from './product-detail.component';
import { ProductEditComponent } from './product-edit.component';
import { ConvertToSpacesPipe } from '../shared/convert-to-spaces.pipe';
// import { StarComponent } from '../shared/star.component';
import { SharedModule } from '../shared/shared.module'

// Imports for loading & configuring the in-memory web api
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
import { ProductData } from './product-data';

// import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ProductDetailGuard } from './product-detail.guard';
import { ProductEditGuard } from './product-edit.guard';
import { ReactiveFormsModule } from '@angular/forms';
import {ProductRoutingModule} from './product-routing.module';

// Generated by CLI, then modified
  // ng g m products/product --flat -m app
    // -m app imports into app module

@NgModule({
  declarations: [
    // Moved here
    ProductListComponent,
    ProductDetailComponent,
    ConvertToSpacesPipe,
    // Moved to Shared
    // StarComponent,
    ProductEditComponent,
  ],
  imports: [
    // Moved to Shared
    // CommonModule,
    // FormsModule,
    RouterModule,
    ReactiveFormsModule,
    InMemoryWebApiModule.forRoot(ProductData, { delay: 1000 }),
    SharedModule,
    ProductRoutingModule,
  ]
})
export class ProductModule { }
